id: P003284
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016246
  title: བཀྲས་ལྷུན་རྒྱུད་པ་གྲྭ་ཚང་གི་ཆོས་སྤྱོད
  author: ''
  volumes:
    ca13cf794e8340eba240f20afd9e96fc:
      image_group_id: I00JW501123
      title: ''
      volume_number: 1
      total_pages: 604
    8bbd35bd65d64e32bd9f1846665fe151:
      image_group_id: I00JW501124
      title: ''
      volume_number: 2
      total_pages: 606
    f340e65ac0b546c187fe81387b1fec7e:
      image_group_id: I00JW501125
      title: ''
      volume_number: 3
      total_pages: 626
