id: P003284
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:37.327190
source_metadata:
  id: bdr:W00EGS1016246
  title: བཀྲས་ལྷུན་རྒྱུད་པ་གྲྭ་ཚང་གི་ཆོས་སྤྱོད
  author: ''
  volumes:
    ca13cf794e8340eba240f20afd9e96fc:
      image_group_id: I00JW501123
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
    8bbd35bd65d64e32bd9f1846665fe151:
      image_group_id: I00JW501124
      title: ''
      volume_number: 2
      total_pages: 606
      base_file: v002.txt
    f340e65ac0b546c187fe81387b1fec7e:
      image_group_id: I00JW501125
      title: ''
      volume_number: 3
      total_pages: 626
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
