id: I1384D1FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:29:13+00:00'
last_modified: '2022-06-07T18:50:55.479899+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016246
  title: བཀྲས་ལྷུན་རྒྱུད་པ་གྲྭ་ཚང་གི་ཆོས་སྤྱོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0F0D:
      image_group_id: I00JW501123
      title: ''
      total_pages: 604
      order: 1
      base_file: 0F0D.txt
    F9F5:
      image_group_id: I00JW501124
      title: ''
      total_pages: 606
      order: 2
      base_file: F9F5.txt
    D559:
      image_group_id: I00JW501125
      title: ''
      total_pages: 626
      order: 3
      base_file: D559.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
