id: I1384D1FE
legacy_id: P003284
ocr_import_info:
  bdrc_scan_id: W00EGS1016246
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T21:24:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  parser_link: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-28T07:25:03.607157+00:00'
last_modified: 2022-09-28 12:55:50.892868
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016246
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016246
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀྲས་ལྷུན་རྒྱུད་པ་གྲྭ་ཚང་གི་ཆོས་སྤྱོད།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.6230962133851753
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I00JW501124:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501124
      total_pages: 606
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00JW501124.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5711879893049362
    legacy_id: v002
  I00JW501123:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501123
      total_pages: 604
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00JW501123.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6701708662132584
    legacy_id: v001
  I00JW501125:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501125
      total_pages: 626
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00JW501125.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.641624158472926
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
